---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install Update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.14.3/terraform_1.14.3_darwin_arm64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: vboxuser
      group: vboxuser

- hosts: web_servers
  become: true
  tasks:


  - name: install apache and php for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Change email address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin changed@yahoo.com
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file to site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: vboxuser
      group: vboxuser
      mode: 0644

  - name: install apache and php for CentOS
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

- hosts: db_server
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: insta  mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package (CentOS)
    tags: samba
    package:
      name: samba
      state: latest
